# parâmetros fixos
TOTAL_WHITE = 1.0
TOTAL_NON_WHITE = 7.0
TOTAL_BLACK = TOTAL_NON_WHITE
TOTAL_RED = TOTAL_NON_WHITE
TOTAL_ROLLS = TOTAL_NON_WHITE + TOTAL_WHITE
PROPORTION_OF_WIN_NON_WHITE = 2.0
PROPORTION_OF_WIN_WHITE = 20.0
WHITE_ROLL_CHANCE = 0.01  # baseado em observação
NON_WHITE_ROLL_CHANCE = 1 - WHITE_ROLL_CHANCE
BLACK_ROLL_CHANCE = NON_WHITE_ROLL_CHANCE / 2.0
RED_ROLL_CHANCE = NON_WHITE_ROLL_CHANCE / 2.0
# parâmetros variáveis
WINDOW_SIZE = 100
START_MONEY = 100.0
STOP_LOSS = 20.0
MAX_BET = 500.0
